### ISSUE TITLE
Broken example: calc

### ISSUE THREAD

**Issue by Vaguery** [lspector/Clojush#101]
`lein run clojush.problems.software.calc` produces

~~~ text
Number of tests: 10
Behaviors: [{:old-tests [[[:zero] 0.0 false] [[:one] 1.0 false] [[:two] 2.0 false] [[:three] 3.0 false] [[:four] 4.0 false] [[:five] 5.0 false] [[:six] 6.0 false] [[:seven] 7.0 false] [[:eight] 8.0 false] [[:nine] 9.0 false]], :new-tests [], :augment-fn #<calc$fn__3822 clojush.problems.software.calc$fn__3822@47ca32f7>} {:old-tests [], :new-tests [], :augment-fn #<calc$fn__3824 clojush.problems.software.calc$fn__3824@78d15e01>} {:old-tests [], :new-tests [], :augment-fn #<calc$fn__3831 clojush.problems.software.calc$fn__3831@7af32927>}]
Exception in thread "main" java.lang.AssertionError: Assert failed: Argument key :ultra-mutates-to-parentheses-frequently is not a recognized argument to pushgp.
(contains? (clojure.core/deref push-argmap) argkey)
	at clojush.pushgp.pushgp$load_push_argmap.invoke(pushgp.clj:134)
	at clojush.pushgp.pushgp$pushgp.invoke(pushgp.clj:257)
	at clojush.core$_main.doInvoke(core.clj:38)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:415)
	at user$eval5.invoke(form-init886434695797924965.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6619)
	at clojure.lang.Compiler.eval(Compiler.java:6609)
	at clojure.lang.Compiler.load(Compiler.java:7064)
	at clojure.lang.Compiler.loadFile(Compiler.java:7020)
	at clojure.main$load_script.invoke(main.clj:294)
	at clojure.main$init_opt.invoke(main.clj:299)
	at clojure.main$initialize.invoke(main.clj:327)
	at clojure.main$null_opt.invoke(main.clj:362)
	at clojure.main$main.doInvoke(main.clj:440)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:419)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.Var.applyTo(Var.java:532)
	at clojure.main.main(main.java:37)
~~~

**Comment by lspector** [comment]
Thanks. This is a known issue that's noted at the top of the file (with a spelling error, alas). It should be fixed or moved back to /experimental, where it used to live.

 -Lee


> On Feb 20, 2015, at 8:03 AM, Bill Tozier <notifications@github.com> wrote:
> 
> lein run clojush.problems.software.calc produces
> 
> Number of tests: 10
> Behaviors: [{:old-tests [[[:zero] 0.0 false] [[:one] 1.0 false] [[:two] 2.0 false] [[:three] 3.0 false] [[:four] 4.0 false] [[:five] 5.0 false] [[:six] 6.0 false] [[:seven] 7.0 false] [[:eight] 8.0 false] [[:nine] 9.0 false]], :new-tests [], :augment-fn #<calc$fn__3822 clojush.problems.software.calc$fn__3822@47ca32f7>} {:old-tests [], :new-tests [], :augment-fn #<calc$fn__3824 clojush.problems.software.calc$fn__3824@78d15e01>} {:old-tests [], :new-tests [], :augment-fn #<calc$fn__3831 clojush.problems.software.calc$fn__3831@7af32927>}]
> Exception in thread "main" java.lang.AssertionError: Assert failed: Argument key :ultra-mutates-to-parentheses-frequently is not a recognized argument to pushgp.
> (contains? (clojure.core/deref push-argmap) argkey)
>     at clojush.pushgp.pushgp$load_push_argmap.invoke(pushgp.clj:134)
>     at clojush.pushgp.pushgp$pushgp.invoke(pushgp.clj:257)
>     at clojush.core$_main.doInvoke(core.clj:38)
>     at clojure.lang.RestFn.invoke(RestFn.java:408)
>     at clojure.lang.Var.invoke(Var.java:415)
>     at user$eval5.invoke(form-init886434695797924965.clj:1)
>     at clojure.lang.Compiler.eval(Compiler.java:6619)
>     at clojure.lang.Compiler.eval(Compiler.java:6609)
>     at clojure.lang.Compiler.load(Compiler.java:7064)
>     at clojure.lang.Compiler.loadFile(Compiler.java:7020)
>     at clojure.main$load_script.invoke(main.clj:294)
>     at clojure.main$init_opt.invoke(main.clj:299)
>     at clojure.main$initialize.invoke(main.clj:327)
>     at clojure.main$null_opt.invoke(main.clj:362)
>     at clojure.main$main.doInvoke(main.clj:440)
>     at clojure.lang.RestFn.invoke(RestFn.java:421)
>     at clojure.lang.Var.invoke(Var.java:419)
>     at clojure.lang.AFn.applyToHelper(AFn.java:163)
>     at clojure.lang.Var.applyTo(Var.java:532)
>     at clojure.main.main(main.java:37)
> —
> Reply to this email directly or view it on GitHub <https://github.com/lspector/Clojush/issues/101>.
> 

--
Lee Spector, Professor of Computer Science
Director, Institute for Computational Intelligence
Cognitive Science, Hampshire College
893 West Street, Amherst, MA 01002-3359
lspector@hampshire.edu, http://hampshire.edu/lspector/
Phone: 413-559-5352, Fax: 413-559-5438

**Comment by Vaguery** [comment]
Is this ready to be closed now?

**Comment by thelmuth** [comment]
Nope. The file hasn't changed in 5 months. Still broken.

**Comment by Vaguery** [comment]
It looks like a cool project. Maybe somebody (me?) can update it. But yeah maybe "deprecated" would be a good folder.

**Comment by Vaguery** [comment]
Is this by any chance closable? Seems like it might have been fixed?

**Comment by lspector** [comment]
Supposedly fixed, but I've only tested that it doesn't raise an exception. I think that Frode (a student in my group), who updated this after the Plush transition, only claimed about the same thing. So we could close this issue but it'd be nice if someone else looked at and ran it a bit more.
